### ISSUE TITLE
userconfig.service hangs when using new config menu for flashing

### ISSUE THREAD

**Issue by nilskuhn** [RPi-Distro/userconf-pi#5] opened 2023-01-19 11:25 UTC
I opened an issue in rpi-imager, but they are pointing it to userconfig-pi project:
https://github.com/raspberrypi/rpi-imager/issues/540
Maybe somebody can take a look?
Thanks

**Comment by XECDesign** [comment] 2023-01-19 11:33
My thinking is that blocking multi-user.target isn't an error here. The initial user account hasn't been configured yet. It's still in a setup mode rather than a multi-user environment.

**Comment by martinka** [comment] 2023-02-11 17:51
I hit this same problem.. Details in https://github.com/thomasjacquin/allsky/issues/2086 .. basically if I don't set a password for the user ( I don't want one since I am using ssh keys) the userconf services never finishes.  Is there a way we can not have userconf prompt for a password when ssh keys are set?

**Comment by Cugar15** [comment] 2023-12-12 10:42
I hit the identical problem today with raspios 32-bit lite.

This is a bit annoying since the issue is not really obvious at first hand and it takes a while to get to understand what is happening.

From this ticket here, I cannot figure out whether this is an accepted issue and when a fix will be provided.

Thanks for commenting.

**Comment by laundmo** [comment] 2024-02-06 13:27
There is a default user, pi, with a default password (or none in case of ssh keys). There is also, of course, the root user. For many usecases, espeically Lite/Headless ones, i don't see a reason to create yet another user.
 
 Please advise on how to skip this step, or at least complete it. i can see the service trying to prompt for a username but no way to fill out this prompt.

**Comment by XECDesign** [comment] 2024-02-06 13:33
There is no default password on any of our current images. How was it set in your case?

If somebody who understands the current behaviour can concisely explain how it's a problem for them, I can provide more information and/or fix whatever issues there might be.

For now, I'm closing since it's behaving as intended.

**Closed as not planned by XECDesign** 2024-02-06 13:33 UTC

**Comment by rkraneis** [comment] 2025-12-17 12:51
Oh, the behaviour is a bit unobvious and not well documented. Installed the lite OS and was also stuck with the issue until I switched through all available consoles. And on 8 I was greeted with the text based initial setup 🤷
